# Generated by Django 3.1.3 on 2021-07-27 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'blank': '이메일을 입력해주세요.', 'max_length': '이메일은 255글자 이하로 입력해주세요.', 'required': '이메일을 입력해주세요.', 'unique': '이미 존재하는 이메일입니다.'}, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='이메일')),
                ('password', models.CharField(error_messages={'blank': '비밀번호를 입력해주세요.', 'invalid': '패스워드가 일치하지 않습니다.', 'max_length': '비밀번호는 128글자 이하로 입력해주세요.', 'min_length': '비밀번호의 길이는 8자 이상이어야 합니다.', 'required': '비밀번호를 입력해주세요.'}, max_length=128, verbose_name='패스워드')),
                ('name', models.CharField(error_messages={'blank': '이름을 입력해주세요.', 'max_length': '이름은 25글자 이하로 입력해주세요.', 'required': '이름을 입력해주세요.'}, max_length=10, verbose_name='이름')),
                ('verifying_number', models.CharField(max_length=6, verbose_name='인증번호')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, error_messages={'blank': '비밀번호를 입력해주세요.', 'invalid': '패스워드가 일치하지 않습니다.', 'max_length': '비밀번호는 128글자 이하로 입력해주세요.', 'min_length': '비밀번호의 길이는 8자 이상이어야 합니다.', 'required': '비밀번호를 입력해주세요.'}, verbose_name='회원가입 일시')),
                ('is_verified', models.BooleanField(default=False, error_messages={'blank': '계정 인증 여부를 입력해주세요.', 'invalid': '계정 인증 여부가 올바르지 않습니다.', 'required': '계정 인증 여부를 입력해주세요.'})),
                ('is_active', models.BooleanField(default=False, error_messages={'blank': '계정을 활성화/비활성화 시킬지 입력해주세요.', 'invalid': '계정을 활성화 여부가 올바르지 않습니다.', 'required': '계정을 활성화/비활성화 시킬지 입력해주세요.'})),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
    ]
