# Generated by Django 3.1.3 on 2021-08-12 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210729_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, error_messages={'blank': '계정을 활성화/비활성화 시킬지 입력해주세요.', 'invalid': '계정을 활성화 여부가 올바르지 않습니다.', 'required': '계정을 활성화/비활성화 시킬지 입력해주세요.'}, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, error_messages={'blank': '계정 인증 여부를 입력해주세요.', 'invalid': '계정 인증 여부가 올바르지 않습니다.', 'required': '계정 인증 여부를 입력해주세요.'}, verbose_name='인증 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, error_messages={'blank': '비밀번호를 입력해주세요.', 'invalid': '패스워드가 일치하지 않습니다.', 'max_length': '비밀번호는 128글자 이하로 입력해주세요.', 'min_length': '비밀번호의 길이는 8자 이상이어야 합니다.', 'required': '비밀번호를 입력해주세요.'}, verbose_name='회원가입 일시'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verifying_number',
            field=models.CharField(blank=True, error_messages={'invalid': '인증번호는 6자리입니다', 'max_length': '인증번호는 6자리입니다.', 'min_length': '인증번호는 6자리입니다.', 'required': '인증번호를 입력해주세요'}, max_length=6, null=True, verbose_name='인증번호'),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_frined', models.BooleanField(verbose_name='친구 여부')),
                ('request_date', models.DateTimeField(auto_now_add=True, error_messages={'blank': '비밀번호를 입력해주세요.', 'invalid': '패스워드가 일치하지 않습니다.', 'max_length': '비밀번호는 128글자 이하로 입력해주세요.', 'min_length': '비밀번호의 길이는 8자 이상이어야 합니다.', 'required': '비밀번호를 입력해주세요.'}, verbose_name='친구 요청일')),
                ('accept_date', models.DateTimeField(blank=True, error_messages={'blank': '비밀번호를 입력해주세요.', 'invalid': '패스워드가 일치하지 않습니다.', 'max_length': '비밀번호는 128글자 이하로 입력해주세요.', 'min_length': '비밀번호의 길이는 8자 이상이어야 합니다.', 'required': '비밀번호를 입력해주세요.'}, null=True, verbose_name='친구 수락일')),
                ('friend_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_user_friends', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
