# Generated by Django 3.1.3 on 2021-08-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210812_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='is_frined',
            new_name='is_friend',
        ),
    ]
