# Generated by Django 3.1.3 on 2021-08-12 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210812_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, error_messages={'blank': '비밀번호를 입력해주세요.', 'invalid': '패스워드가 일치하지 않습니다.', 'max_length': '비밀번호는 128글자 이하로 입력해주세요.', 'min_length': '비밀번호의 길이는 8자 이상이어야 합니다.', 'required': '비밀번호를 입력해주세요.'}, verbose_name='친구 요청일'),
        ),
    ]
