# Generated by Django 3.1.3 on 2021-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210812_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='is_friend',
            field=models.BooleanField(default=False, verbose_name='친구 여부'),
        ),
    ]
