# Generated by Django 3.1.3 on 2021-08-12 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='is_show',
        ),
        migrations.AddField(
            model_name='feed',
            name='access_permission',
            field=models.SmallIntegerField(choices=[(0, '비공개'), (1, '전체 공개'), (2, '친구 공개')], default=1, verbose_name='피드 접근 권한'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='contents',
            field=models.CharField(max_length=2000, verbose_name='본문'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='피드 등록일'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='thumbnail',
            field=models.CharField(max_length=100, verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
